### ISSUE TITLE
Pull requests in vain?

### ISSUE THREAD

**Issue by francwalter** [ozh/lightbox-clones#3]
As I see there is one only pull request from feb. 15 (UPDATED: Fancybox #2 opened on 12 Feb by MarQuisKnox) which never got pulled?
I thougt to contribute, because the links on the page are many 404, but if there is no more action here I better wont.
So dead here or not?
Seems to be all very very old and nothing works there anymore.
Dead.

**Comment by ozh** [comment]
Not dead. Totally missed that PR though, I admit :)

**Comment by francwalter** [comment]
So will you pull it now?
